=== R-CF/zarr_conventions_cs/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Coordinate Set Convention",
  "description": "Schema for the coordinate set convention",
  "type": "object",
  "properties": {
    "zarr_format": {
      "type": "integer",
      "enum": [2, 3],
      "description": "Zarr format version"
    },
    "node_type": {
      "type": "string",
      "enum": ["array", "group"],
      "description": "Type of Zarr node"
    },
    "shape": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "dimension_names": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
      }
    },
    "attributes": {
      "type": "object",
      "description": "Zarr attributes containing convention metadata and properties",
      "properties": {
        "zarr_conventions": {
          "type": "array",
          "description": "Array of convention metadata objects",
          "contains": {
            "$ref": "#/$defs/conventionMetadata"
          }
        }
      },
      "required": ["zarr_conventions"]
    }
  },
  "required": ["zarr_format", "node_type", "attributes"],
  "if": {
    "properties": {
      "node_type": { "const": "array"}
    }
  },
  "then": {
    "required": ["shape", "dimension_names"],
    "properties": {
      "attributes": {
        "type": "object",
        "required": ["cs"],
        "properties": {
          "cs": {
            "$ref": "#/$defs/cs"
          }
        }
      }
    }
  },
  "else": {
    "properties": {
      "attributes": {
        "type": "object",
        "required": ["crs"],
        "properties": {
          "crs": {
            "type": "object",
            "description": "Keyed CRS objects stored in a Zarr group, keyed by CRS name",
            "minProperties": 1,
            "additionalProperties": {
              "$ref": "#/$defs/crs"
            }
          }
        }
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "conventionMetadata": {
      "type": "object",
      "description": "Convention metadata object for use in zarr_conventions array",
      "properties": {
        "schema_url": {
          "type": "string",
          "const": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
          "description": "URL to the JSON Schema definition for this convention"
        },
        "spec_url": {
          "type": "string",
          "const": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/README.md",
          "description": "URL to the full specification document"
        },
        "uuid": {
          "type": "string",
          "const": "e4dbf0b7-7a00-4ce6-b23e-484292014ab4",
          "description": "UUID that permanently identifies this convention"
        },
        "name": {
          "type": "string",
          "description": "cs"
        },
        "description": {
          "type": "string",
          "const": "Coordinate set convention for Zarr arrays",
          "description": "Convention to assign semantic meaning to the dimensions of Zarr arrays, using axes and coordinates"
        }
      },
      "anyOf": [
        { "required": ["schema_url"] },
        { "required": ["spec_url"] },
        { "required": ["uuid"] }
      ],
      "additionalProperties": false
    },
    "cs": {
      "type": "object",
      "description": "Coordinate set for n-dimensional arrays",
      "properties": {
        "name": {
          "type": "string",
          "description": "Descriptive name for the coordinate set."
        },
        "crs": {
          "type": "array",
          "items": {
            "oneOf": [
              { "$ref": "#/$defs/crs" },
              { "$ref": "https://raw.githubusercontent.com/R-CF/zarr_convention_ref/main/schema.json#/$defs/ref" }
            ]
          }
        },
        "id": {
          "$ref": "https://raw.githubusercontent.com/zarr-conventions/geo-proj/main/schema.json#/$defs/projAttributes"
        }
      },
      "required": ["crs"]
    },
    "crs": {
      "type": "object",
      "description": "CRS definition.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Descriptive name for the coordinate reference system."
        },
        "axes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/axis"
          }
        },
        "id": {
          "$ref": "https://raw.githubusercontent.com/zarr-conventions/geo-proj/main/schema.json#/$defs/projAttributes"
        },
        "geolocation": {
          "$ref": "https://raw.githubusercontent.com/R-CF/zarr_convention_geolocation/main/schema.json#/$defs/geolocation"
        }
      },
      "required": ["axes"],
      "additionalProperties": true
    },
    "axis": {
      "type": "object",
      "description": "Properties of an individual axis.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the axis. Required."
        },
        "abbreviation": {
          "type": "string",
          "description": "Abbreviation of the axis, such as \"X\" or \"Y\"."
        },
        "direction": {
          "type": "string",
          "description": "The direction of increasing coordinate values. Its value must be taken from Table 48 of OGC standard \"Referencing by Coordinates\"."
        },
        "coordinates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/coordinates"
          }
        }
      },
      "required": ["name"],
      "additionalProperties": true
    },
    "coordinates": {
      "type": "object",
      "description": "Properties of a set of coordinates",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the set of coordinates."
        },
        "unit": {
          "oneOf": [
            { "type": "string" },
            { "$ref": "https://raw.githubusercontent.com/clbarnes/zarr-convention-uom/refs/tags/v1/schema.json#/$defs/uom" }
          ]
        },
        "time": {
          "$ref": "#/$defs/time"
        },
        "values": {
          "$ref": "#/$defs/values"
        },
        "boundaries": {
          "$ref": "#/$defs/boundaries"
        },
        "parametric": {
          "$ref": "#/$defs/parametric"
        }
      },
      "required": ["values"],
      "additionalProperties": true
    },
    "time": {
      "type": "object",
      "description": "The time definition of a set of coordinates.",
      "properties": {
        "unit": {
          "type": "string"
        },
        "epoch": {
          "type": "string"
        },
        "calendar": {
          "type": "string"
        }
      },
      "required": ["unit", "epoch"],
      "additionalProperties": true
    },
    "values": {
      "type": "object",
      "description": "The coordinate values of an axis",
      "properties": {
        "regular": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "description": "Initial coordinate value (at shape index 0) and increment between successive coordinates.",
          "minItems": 2,
          "maxItems": 2
        },
        "external": {
          "$ref": "https://raw.githubusercontent.com/R-CF/zarr_convention_ref/main/schema.json#/$defs/ref",
          "description": "Reference to a 1-dimensional array with coordinate values."
        },
        "explicit": {
          "type": "array",
          "description": "JSON array of coordinate values."
        }
      },
      "oneOf": [
        { "required": ["regular"] },
        { "required": ["external"] },
        { "required": ["explicit"] }
      ],
      "additionalProperties": true
    },
    "boundaries": {
      "type": "object",
      "description": "The boundary values around coordinate values of an axis",
      "properties": {
        "regular": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "description": "JSON array with the extent below and above the coordinate value.",
          "minItems": 2,
          "maxItems": 2
        },
        "external": {
          "$ref": "https://raw.githubusercontent.com/R-CF/zarr_convention_ref/main/schema.json#/$defs/ref",
          "description": "Path to an array providing boundary values."
        }
      },
      "oneOf": [
        { "required": ["regular"] },
        { "required": ["external"] }
      ],
      "additionalProperties": true
    },
    "parametric": {
      "type": "object",
      "description": "Formula and terms for parametric coordinates",
      "properties": {
        "formula": {
          "type": "string"
        },
        "crs": {
          "type": "object",
          "description": "Keyed values objects, keyed by name of the formula term",
          "minProperties": 1,
          "additionalProperties": {
            "$ref": "#/$defs/values"
          }
        }
      },
      "required": ["formula", "terms"]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/CMIP6_Amon.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [1200, 180, 288],
  "dimension_names": ["time", "lat", "lon"],
  "attributes": {
    "zarr_conventions": [
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
        "name": "cs"
      },
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_ref/main/schema.json",
        "name": "ref"
      }
    ],
    "cs": {
      "crs": [
        {
          "name": "WGS84",
          "axes": {
            "lon": {
              "abbreviation": "X",
              "coordinates": [
                {
                  "direction": "east",
                  "unit": "degrees",
                  "values": {
                    "regular": [0.625, 1.25]
                  },
                  "boundaries": {
                    "regular": [-0.625, 0.625]
                  }
                }
              ]
            },
            "lat": {
              "abbreviation": "Y",
              "coordinates": [
                {
                  "direction": "north",
                  "unit": "degrees",
                  "values": {
                    "regular": [-89.5, 1]
                  },
                  "boundaries": {
                    "regular": [-0.5, 0.5]
                  }
                }
              ]
            }
          }
        },
        {
          "name": "Temporal scale based on the 'noleap' model calendar.",
          "axes": {
            "time": {
              "abbreviation": "T",
              "coordinates": [
                {
                  "direction": "future",
                  "time": {
                    "unit": "day",
                    "epoch": "1850-01-01",
                    "calendar": "noleap"
                  },
                  "values": {
                    "external": {
                      "ref": {
                        "node": "../time"
                      }
                    }
                  },
                  "boundaries": {
                    "external": {
                      "ref": {
                        "node": "../time_bnds"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/cordex.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [1800, 412, 424],
  "dimension_names": ["time", "rlat", "rlon"],
  "attributes": {
    "zarr_conventions": [
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
        "name": "cs"
      },
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_geolocation/main/schema.json",
        "name": "geolocation"
      },
      {
        "schema_url": "https://raw.githubusercontent.com/zarr-conventions/geo-proj/main/schema.json",
        "name": "proj"
      }
    ],
    "cs": {
      "crs": [
        {
          "name": "rotated pole grid for CORDEX EUR-11 domain",
          "axes": [
            {
              "name": "rlon",
              "abbreviation": "X",
              "coordinates": [
                {
                  "direction": "east",
                  "unit": "degrees",
                  "values": {
                    "regular": [-28.375, 0.11]
                  }
                }
              ]
            },
            {
              "name": "rlat",
              "abbreviation": "Y",
              "coordinates": [
                {
                  "direction": "north",
                  "unit": "degrees",
                  "values": {
                    "regular": [-23.375, 0.11]
                  }
                }
              ]
            }
          ],
          "geolocation": {
            "geodetic": {
              "x": {
                "node": "lon"
              },
              "y": {
                "node": "lat"
              },
              "crs": {
                "proj:code": "EPSG:4326"
              }
            }
          }
        },
        {
          "name": "Temporal scale based on the '360_day' model calendar.",
          "axes": [
            {
              "name": "time",
              "abbreviation": "T",
              "coordinates": [
                {
                  "direction": "future",
                  "time": {
                    "unit": "day",
                    "epoch": "1949-12-01",
                    "calendar": "360_day"
                  },
                  "values": {
                    "regular": [20190.5, 1]
                  },
                  "boundaries": {
                    "regular": [-0.5, 0.5]
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/geo_region.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [1, 23],
  "dimension_names": ["time", "geo_region"],
  "attributes": {
    "zarr_conventions": [
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
        "name": "cs"
      }
    ],
    "cs": {
      "crs": [
        {
          "axes": [
            {
              "name": "geo_region",
              "coordinates": [
                {
                  "values": {
                    "explicit": ["Anglian", "Argyll", "Clyde", "Dee", "Forth", "Humber", "Neagh Bann", "North East Scotland", "North Eastern Ireland", "North Highland", "North West England", "North Western Ireland", "Northumbria", "Orkney and Shetland", "Severn", "Solway", "South East England", "South West England", "Tay", "Thames", "Tweed", "West Highland", "Western Wales"]
                  }
                }
              ]
            }
          ]
        },
        {
          "axes": [
            {
              "name": "time",
              "abbreviation": "T",
              "coordinates": [
                {
                  "direction": "future",
                  "time": {
                    "reference": "hours since 1800-01-01",
                    "calendar": "standard"
                  },
                  "values": {
                    "explicit": [1678608]
                  },
                  "boundaries": {
                    "regular": [-4344, 258624]
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/CMIP6_day.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [8605, 180, 288],
  "dimension_names": ["time", "lat", "lon"],
  "attributes": {
    "zarr_conventions": [
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
        "name": "cs"
      },
      {
        "schema_url": "https://raw.githubusercontent.com/zarr-conventions/geo-proj/main/schema.json",
        "name": "proj:"
      }
    ],
    "cs": {
      "crs": [
        {
          "name": "WGS84",
          "axes": [
            {
              "name": "lon",
              "abbreviation": "X",
              "coordinates": [
                {
                  "direction": "east",
                  "unit": "degrees",
                  "values": {
                    "regular": [0.625, 1.25]
                  },
                  "boundaries": {
                    "regular": [-0.625, 0.625]
                  }
                }
              ]
            },
            {
              "name": "lat",
              "abbreviation": "Y",
              "coordinates": [
                {
                  "direction": "north",
                  "unit": "degrees",
                  "values": {
                    "regular": [-89.5, 1]
                  },
                  "boundaries": {
                    "regular": [-0.5, 0.5]
                  }
                }
              ]
            }
          ],
          "id": {
            "proj:code": "EPSG:4326"
          }
        },
        {
          "name": "Temporal scale based on the 'noleap' model calendar.",
          "axes": [
            {
              "name": "time",
              "abbreviation": "T",
              "coordinates": [
                {
                  "direction": "future",
                  "time": {
                    "reference": "days since 1850-01-01",
                    "calendar": "noleap"
                  },
                  "values": {
                    "regular": [27895.5, 1]
                  },
                  "boundaries": {
                    "regular": [-0.5, 0.5]
                  }
                }
              ]
            }
          ]
        },
        {
          "name": "Height above surface for standard meteorological measurements.",
          "axes": [
            {
              "name": "height",
              "abbreviation": "Z",
              "coordinates": [
                {
                  "direction": "up",
                  "unit": "meter",
                  "values": {
                    "explicit": [2]
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/sentinel-1.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [25000, 16000],
  "dimension_names": ["azimuth_time", "ground_range"],
  "attributes": {
    "zarr_conventions": [
      { "name": "cs",
        "uuid": "e4dbf0b7-7a00-4ce6-b23e-484292014ab4"
      },
      { "name": "geolocation",
        "uuid": "bb9ee930-8c60-4c47-ad6b-8daa558987ed"
      }
    ],
    "cs": {
      "name": "Sentinel-1 GRD native geometry",
      "crs": [
        {
          "type": "temporal",
          "description": "Zero-Doppler azimuth time",
          "axes": {
            "azimuth_time": {
              "abbreviation": "T",
              "direction": "future",
              "coordinates": [{
                "time": {
                  "unit": "ms",
                  "epoch": "2024-03-15T06:12:00Z",
                  "calendar": "standard"
                },
                "values": { "regular": [0.0, 2.055] },
                "boundaries": { "regular": [-1.0275, 1.0275] }
              }]
            }
          }
        },
        {
          "type": "undefined",
          "description": "Ground range distance from sub-satellite track",
          "axes": {
            "ground_range": {
              "direction": "away",
              "coordinates": [{
                "unit": "m",
                "values": { "regular": [0.0, 10.0] },
                "boundaries": { "regular": [-5.0, 5.0] }
              }]
            }
          },
          "geolocation": {
            "geodetic": {
              "x": { "node": "../lon" },
              "y": { "node": "../lat" },
              "crs": {
                "proj:code": "EPSG:4326"
              }
            }
          }
        }
      ]
    }
  }
}

=== R-CF/zarr_conventions_cs/examples/CRU_array.json
{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [1464, 360, 720],
  "dimension_names": ["time", "lat", "lon"],
  "attributes": {
    "zarr_conventions": [
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_cs/main/schema.json",
        "name": "cs"
      },
      {
        "schema_url": "https://raw.githubusercontent.com/R-CF/zarr_convention_ref/main/schema.json",
        "name": "ref"
      }
    ],
    "cs": {
      "crs": [
        {
          "node": "..",
          "attribute": "/attributes/crs/WGS84"
        },
        {
          "node": "..",
          "attribute": "/attributes/crs/standard_calendar"
        }
      ]
    }
  }
}
